/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WithdrawalService } from "../withdrawal.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WithdrawalCreateInput } from "./WithdrawalCreateInput";
import { Withdrawal } from "./Withdrawal";
import { WithdrawalFindManyArgs } from "./WithdrawalFindManyArgs";
import { WithdrawalWhereUniqueInput } from "./WithdrawalWhereUniqueInput";
import { WithdrawalUpdateInput } from "./WithdrawalUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WithdrawalControllerBase {
  constructor(
    protected readonly service: WithdrawalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Withdrawal })
  @nestAccessControl.UseRoles({
    resource: "Withdrawal",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: WithdrawalCreateInput,
  })
  async createWithdrawal(
    @common.Body() data: WithdrawalCreateInput
  ): Promise<Withdrawal> {
    return await this.service.createWithdrawal({
      data: data,
      select: {
        amount: true,
        artistProfile: true,
        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Withdrawal] })
  @ApiNestedQuery(WithdrawalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Withdrawal",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async withdrawals(@common.Req() request: Request): Promise<Withdrawal[]> {
    const args = plainToClass(WithdrawalFindManyArgs, request.query);
    return this.service.withdrawals({
      ...args,
      select: {
        amount: true,
        artistProfile: true,
        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Withdrawal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Withdrawal",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async withdrawal(
    @common.Param() params: WithdrawalWhereUniqueInput
  ): Promise<Withdrawal | null> {
    const result = await this.service.withdrawal({
      where: params,
      select: {
        amount: true,
        artistProfile: true,
        createdAt: true,
        date: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Withdrawal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Withdrawal",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: WithdrawalUpdateInput,
  })
  async updateWithdrawal(
    @common.Param() params: WithdrawalWhereUniqueInput,
    @common.Body() data: WithdrawalUpdateInput
  ): Promise<Withdrawal | null> {
    try {
      return await this.service.updateWithdrawal({
        where: params,
        data: data,
        select: {
          amount: true,
          artistProfile: true,
          createdAt: true,
          date: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Withdrawal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Withdrawal",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWithdrawal(
    @common.Param() params: WithdrawalWhereUniqueInput
  ): Promise<Withdrawal | null> {
    try {
      return await this.service.deleteWithdrawal({
        where: params,
        select: {
          amount: true,
          artistProfile: true,
          createdAt: true,
          date: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
