/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { IncomeReportService } from "../incomeReport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { IncomeReportCreateInput } from "./IncomeReportCreateInput";
import { IncomeReport } from "./IncomeReport";
import { IncomeReportFindManyArgs } from "./IncomeReportFindManyArgs";
import { IncomeReportWhereUniqueInput } from "./IncomeReportWhereUniqueInput";
import { IncomeReportUpdateInput } from "./IncomeReportUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class IncomeReportControllerBase {
  constructor(
    protected readonly service: IncomeReportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: IncomeReport })
  @nestAccessControl.UseRoles({
    resource: "IncomeReport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: IncomeReportCreateInput,
  })
  async createIncomeReport(
    @common.Body() data: IncomeReportCreateInput
  ): Promise<IncomeReport> {
    return await this.service.createIncomeReport({
      data: data,
      select: {
        artistProfile: true,
        commissionPaid: true,
        createdAt: true,
        id: true,
        month: true,
        totalIncome: true,
        transactions: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [IncomeReport] })
  @ApiNestedQuery(IncomeReportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "IncomeReport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async incomeReports(@common.Req() request: Request): Promise<IncomeReport[]> {
    const args = plainToClass(IncomeReportFindManyArgs, request.query);
    return this.service.incomeReports({
      ...args,
      select: {
        artistProfile: true,
        commissionPaid: true,
        createdAt: true,
        id: true,
        month: true,
        totalIncome: true,
        transactions: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: IncomeReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IncomeReport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async incomeReport(
    @common.Param() params: IncomeReportWhereUniqueInput
  ): Promise<IncomeReport | null> {
    const result = await this.service.incomeReport({
      where: params,
      select: {
        artistProfile: true,
        commissionPaid: true,
        createdAt: true,
        id: true,
        month: true,
        totalIncome: true,
        transactions: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: IncomeReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IncomeReport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: IncomeReportUpdateInput,
  })
  async updateIncomeReport(
    @common.Param() params: IncomeReportWhereUniqueInput,
    @common.Body() data: IncomeReportUpdateInput
  ): Promise<IncomeReport | null> {
    try {
      return await this.service.updateIncomeReport({
        where: params,
        data: data,
        select: {
          artistProfile: true,
          commissionPaid: true,
          createdAt: true,
          id: true,
          month: true,
          totalIncome: true,
          transactions: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: IncomeReport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "IncomeReport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteIncomeReport(
    @common.Param() params: IncomeReportWhereUniqueInput
  ): Promise<IncomeReport | null> {
    try {
      return await this.service.deleteIncomeReport({
        where: params,
        select: {
          artistProfile: true,
          commissionPaid: true,
          createdAt: true,
          id: true,
          month: true,
          totalIncome: true,
          transactions: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
