/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ArtistProfileService } from "../artistProfile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArtistProfileCreateInput } from "./ArtistProfileCreateInput";
import { ArtistProfile } from "./ArtistProfile";
import { ArtistProfileFindManyArgs } from "./ArtistProfileFindManyArgs";
import { ArtistProfileWhereUniqueInput } from "./ArtistProfileWhereUniqueInput";
import { ArtistProfileUpdateInput } from "./ArtistProfileUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ArtistProfileControllerBase {
  constructor(
    protected readonly service: ArtistProfileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ArtistProfile })
  @nestAccessControl.UseRoles({
    resource: "ArtistProfile",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ArtistProfileCreateInput,
  })
  async createArtistProfile(
    @common.Body() data: ArtistProfileCreateInput
  ): Promise<ArtistProfile> {
    return await this.service.createArtistProfile({
      data: {
        ...data,

        inviteCode: data.inviteCode
          ? {
              connect: data.inviteCode,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        bio: true,
        commissionRate: true,
        createdAt: true,
        id: true,

        inviteCode: {
          select: {
            id: true,
          },
        },

        location: true,
        priceRange: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workPortfolio: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ArtistProfile] })
  @ApiNestedQuery(ArtistProfileFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ArtistProfile",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async artistProfiles(
    @common.Req() request: Request
  ): Promise<ArtistProfile[]> {
    const args = plainToClass(ArtistProfileFindManyArgs, request.query);
    return this.service.artistProfiles({
      ...args,
      select: {
        bio: true,
        commissionRate: true,
        createdAt: true,
        id: true,

        inviteCode: {
          select: {
            id: true,
          },
        },

        location: true,
        priceRange: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workPortfolio: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ArtistProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArtistProfile",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async artistProfile(
    @common.Param() params: ArtistProfileWhereUniqueInput
  ): Promise<ArtistProfile | null> {
    const result = await this.service.artistProfile({
      where: params,
      select: {
        bio: true,
        commissionRate: true,
        createdAt: true,
        id: true,

        inviteCode: {
          select: {
            id: true,
          },
        },

        location: true,
        priceRange: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workPortfolio: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ArtistProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArtistProfile",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: ArtistProfileUpdateInput,
  })
  async updateArtistProfile(
    @common.Param() params: ArtistProfileWhereUniqueInput,
    @common.Body() data: ArtistProfileUpdateInput
  ): Promise<ArtistProfile | null> {
    try {
      return await this.service.updateArtistProfile({
        where: params,
        data: {
          ...data,

          inviteCode: data.inviteCode
            ? {
                connect: data.inviteCode,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          bio: true,
          commissionRate: true,
          createdAt: true,
          id: true,

          inviteCode: {
            select: {
              id: true,
            },
          },

          location: true,
          priceRange: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          workPortfolio: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ArtistProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ArtistProfile",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteArtistProfile(
    @common.Param() params: ArtistProfileWhereUniqueInput
  ): Promise<ArtistProfile | null> {
    try {
      return await this.service.deleteArtistProfile({
        where: params,
        select: {
          bio: true,
          commissionRate: true,
          createdAt: true,
          id: true,

          inviteCode: {
            select: {
              id: true,
            },
          },

          location: true,
          priceRange: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          workPortfolio: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
