/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MoodboardService } from "../moodboard.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MoodboardCreateInput } from "./MoodboardCreateInput";
import { Moodboard } from "./Moodboard";
import { MoodboardFindManyArgs } from "./MoodboardFindManyArgs";
import { MoodboardWhereUniqueInput } from "./MoodboardWhereUniqueInput";
import { MoodboardUpdateInput } from "./MoodboardUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MoodboardControllerBase {
  constructor(
    protected readonly service: MoodboardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Moodboard })
  @nestAccessControl.UseRoles({
    resource: "Moodboard",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MoodboardCreateInput,
  })
  async createMoodboard(
    @common.Body() data: MoodboardCreateInput
  ): Promise<Moodboard> {
    return await this.service.createMoodboard({
      data: data,
      select: {
        clientProfile: true,
        createdAt: true,
        id: true,
        images: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Moodboard] })
  @ApiNestedQuery(MoodboardFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Moodboard",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async moodboards(@common.Req() request: Request): Promise<Moodboard[]> {
    const args = plainToClass(MoodboardFindManyArgs, request.query);
    return this.service.moodboards({
      ...args,
      select: {
        clientProfile: true,
        createdAt: true,
        id: true,
        images: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Moodboard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Moodboard",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async moodboard(
    @common.Param() params: MoodboardWhereUniqueInput
  ): Promise<Moodboard | null> {
    const result = await this.service.moodboard({
      where: params,
      select: {
        clientProfile: true,
        createdAt: true,
        id: true,
        images: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Moodboard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Moodboard",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: MoodboardUpdateInput,
  })
  async updateMoodboard(
    @common.Param() params: MoodboardWhereUniqueInput,
    @common.Body() data: MoodboardUpdateInput
  ): Promise<Moodboard | null> {
    try {
      return await this.service.updateMoodboard({
        where: params,
        data: data,
        select: {
          clientProfile: true,
          createdAt: true,
          id: true,
          images: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Moodboard })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Moodboard",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMoodboard(
    @common.Param() params: MoodboardWhereUniqueInput
  ): Promise<Moodboard | null> {
    try {
      return await this.service.deleteMoodboard({
        where: params,
        select: {
          clientProfile: true,
          createdAt: true,
          id: true,
          images: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
